In [3]:
#20.1

import numpy as np
a_18 = np.array([0,1,2,3,4])
print(a_18)
a_18.ndim
a_18.shape

[0 1 2 3 4]


(5,)

In [5]:
#20.1

import numpy as np
matrik_18 = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
a_18 = np.array(matrik_18)
print(a_18)
a_18.ndim


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


2

In [7]:
#20.1

import numpy as np
matrik_018 = [
    [[1,2,3,4]],
    [[5,6,7,8]],
    [[9,10,11,12]],
    [[13,14,15,16]]
]
a_18 = np.array(matrik_018)
print(a_18)


[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]

 [[13 14 15 16]]]


In [8]:
#20.1

import pandas as pd
matrik = [
    [[1,2,3,4]],
    [[5,6,7,8]],
    [[9,10,11,12]],
    [[13,14,15,16]]
]
for isi in matrik[0:4]:
    print(isi)
c = pd.array
print(c)


[[1, 2, 3, 4]]
[[5, 6, 7, 8]]
[[9, 10, 11, 12]]
[[13, 14, 15, 16]]
<function array at 0x7e26ce2f55a0>


In [11]:
#20.2

import numpy as pd
matrik_18 = ('[1,2,3,4]','[5,6,7,8]','[9,10,11]')
for isi in matrik_18[0:3]:
    print(isi)
c = pd.array(matrik_18)
c.shape
c.ndim
print(c)


[1,2,3,4]
[5,6,7,8]
[9,10,11]
['[1,2,3,4]' '[5,6,7,8]' '[9,10,11]']


In [10]:
#20.3

import numpy as pd
f_18 = pd.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f_18)
f_18[0,0] = 22
print(f_18)
pd.random.randint(1,10,size=(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[22  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[9, 5, 3, 5],
       [2, 7, 9, 7],
       [2, 4, 3, 2]])

In [12]:
#20.3

a_18 = pd.zeros((10,10))
print(a_18)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
#20.3

import numpy as firda
taf_18 = firda.identity(10)
print(taf_18)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [14]:
#20.3

prad_18 = 4*(taf_18)
print(prad_18)

[[4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 4.]]


In [15]:
#20.3

f_18 = firda.ones((6,9))
i_18 = firda.identity(6)*6
print(f_18)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
#20.4

a_18 = np.array([1,2,3,4])
print(a_18)

[1 2 3 4]


In [18]:
frd_18 = a_18
print(frd_18)

[1 2 3 4]


In [25]:
#20.5

a_18+2
np.cos(a_18)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [27]:
#20.6

a_18 = np.array([[1,3,5,7],[2,4,6,8]])
b_18 = np.array([[10,20,30,40],[11,21,31,41]])
c_18 = a_18*b_18
print(a_18)
print(b_18)
print(c_18)


[[1 3 5 7]
 [2 4 6 8]]
[[10 20 30 40]
 [11 21 31 41]]
[[ 10  60 150 280]
 [ 22  84 186 328]]


In [29]:
#20.7

f_18 = [
    [[1,2,3,4]],
    [[5,6,7,8]],
    [[9,10,11,12]],
    [[13,14,15,16]]
]
for isi in f_18[0:4]:
    print(isi)
i_18 = np.min(f_18)
r_18 = np.min(f_18,axis=0)
d_18 = np.max(f_18,axis=0)
a_18 = np.sum(f_18,axis=0)
print(f_18)
print(i_18)
print(r_18)
print(d_18)
print(a_18)

[[1, 2, 3, 4]]
[[5, 6, 7, 8]]
[[9, 10, 11, 12]]
[[13, 14, 15, 16]]
[[[1, 2, 3, 4]], [[5, 6, 7, 8]], [[9, 10, 11, 12]], [[13, 14, 15, 16]]]
1
[[1 2 3 4]]
[[13 14 15 16]]
[[28 32 36 40]]
